### ISSUE TITLE
ZuluSCSI RP2040 Otari Digital Master Problems

### ISSUE THREAD

**Issue by WhatIsTheWeather** [ZuluSCSI/ZuluSCSI-firmware#184] opened 2023-04-26 17:18 UTC
Hi, I hope it is ok to post this here. I have been attempting to get a ZuluSCSI RP2040 working with an Otari DP-3 Audio Digital Master unit with no success thus far. The unit has two SCSI CD drives and I have been attempting to replace one with the ZuluSCSI board and uses a Fujitsu MB866601A SPC IC for the SCSI controller interface. The unit has an option to change the master media type from CD to other playback media such as MO drives and HDDs through switching of a dip switch on the main board so I have tried both options and emulated SCSI device types with no success (CD, HDD and MO drive). I have found no way of identifying the correct SCSI used for the drives so have periodically gone through SCSI IDs 0-7 and the only SCSI ID that seems to somewhat communicate with the machine is ID 0, however when using ID 0 the machine repeatably beeps and does not seem to communicate with the ZuluSCSI board correctly. The only files inside of the image file created are two 16 bit .wav files so nothing complex. 

I have enabled debug mode on the ZuluSCSI and have obtained a log from when using the ZuluSCSI with the image file set to SCSI ID 0. I am honestly pretty stumped with getting this working, after updating the firmware and messing with some of the settings I still have had no luck so thought here would be the best place to attempt to find a solution. 

Attached is the log file from the SD Card.
[zululog.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/11335616/zululog.txt)

[dp-3.pdf](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/11335628/dp-3.pdf) - Here is the very brief manual for the DP-3.

**Comment by aperezbios** [comment] 2023-04-26 20:38
Thanks for reaching out, @WhatIsTheWeather. Can you describe what you have tried so far? I see you're currently specifying Magneto Optical as the device type. Was there a reason for that? The manual you've attached doesn't contain a single mention of SCSI that I could find, so I don't believe it's of much use in this context.

@PetteriAimonen, can you take a look at this log? From what I can tell, everything appears to be functioning as expected from the ZuluSCSI side.

**Comment by PetteriAimonen** [comment] 2023-04-27 06:05
Yes, SCSI communication appears to work fine based on the log. The device beeping sounds like it might not like either the filesystem in the image or the block size.

If you have an image of a CD that works in the CD drive, you could try that with names "CD0_512.iso", "CD0_1024.iso" and "CD0_2048.iso". We have seen some samplers in particular be quite specific about the block size used.

**Comment by WhatIsTheWeather** [comment] 2023-04-28 17:26
> Thanks for reaching out, @WhatIsTheWeather. Can you describe what you have tried so far? I see you're currently specifying Magneto Optical as the device type. Was there a reason for that? The manual you've attached doesn't contain a single mention of SCSI that I could find, so I don't believe it's of much use in this context.
> 
> @PetteriAimonen, can you take a look at this log? From what I can tell, everything appears to be functioning as expected from the ZuluSCSI side.

Thanks for taking the time to reply. So far I have attempted to use wav files packaged into an image in the CD, MO and HDD modes on ZuluSCSI.

When using the Otari with physical media it seems to work best using audio files written as an audio CD/CD-DA but I am unsure how to create an image of an audio cd that is compatible with the ZuluSCSI. I had another mess around with the ZuluSCSI last night and when looking at the logs it seems that the Otari gets stuck looking for the TOC of the audio cd. The manual states that it will also work with a cd burnt as a data cd following the Yellow Book Mode 1 / ISO9660 format but I have never managed to get this format working. 

When I was using the ZuluSCSI image configured as a HDD or MO drive I had set the Otari to the other physical media mode using one of the machines internal dip switches. In the manual there is a small section stating what internal dipswitch has to be changed to enable this mode.

I have also tried to alter the block size to different sizes but that has not allowed the Otari to read the wav files either. 

Does anyone know the best way to image an audio cd to use with the ZuluSCSI as an image files to boot from?

thanks.

**Comment by PetteriAimonen** [comment] 2023-04-28 17:38
ZuluSCSI currently mainly supports data CDs - I'm not sure if CD's with only audio might work, but at least mixed CDs will not - the TOC is just hardcoded currently.

@aperezbios Maybe we should move forward with the bin/cue support to enable audio CDs properly?
Related discussion: #143

**Comment by WhatIsTheWeather** [comment] 2023-05-01 15:10
So I have had a bit more of a mess around with the ZuluSCSI and the Otari attempting to get it working. I successfully created a CD-ROM yellow book mode1 iso9600 data cd that worked with the digital master consisting of two wav files named A and B, even after imaging the CD with imgburn I still had no luck with getting it working with ZuluSCSI. Once again I tried the ZuluSCSI set as a CD, MO and HDD but none seemed to work. I will try again and attach separate logs for each emulation type. It would be great to see bin/cue support implemented to be able to do away with using CDs with this unit. 

Thanks.

**Comment by aperezbios** [comment] 2023-05-01 16:05
@WhatIsTheWeather we'd need to see actual data (eg the log file, with debug mode turned on) to be able to understand what is or is not happening. Without something to analyze, we can only take shots in the dark, which isn't likely to result in a successful outcome. Can you please re-try the test with the ISO you created, but with debug mode turned on, and then send us the resulting zululog.txt file? You can attach it here to this issue.

**Comment by WhatIsTheWeather** [comment] 2023-05-01 17:14
Here is the log file from using the imaged known good cd-rom data cd containing Side A and B 16 bit 44.1 wav files named an and b. I have debug and termination enabled on the ZuluSCSI board. I can provide a wetransfer link to the image used on the sd card if that will help too? 

Thanks. 

[zululog.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/11366802/zululog.txt)

**Comment by PetteriAimonen** [comment] 2023-05-02 06:42
Thanks for the log.
I think the problem is here:

```
[23746ms] DBG ---- SELECTION: 0
[23748ms] DBG ---- COMMAND: CDROM Read TOC
[23748ms] DBG ------ OUT: 0x43 0x00 0x00 0x00 0x00 0x00 
[23749ms] DBG ------ OUT: 0xAA 0x00 0x0C 0x00 
[23749ms] DBG ---- STATUS: 2 CHECK_CONDITION, sense 0x00002400
[26245ms] DBG BUS RESET
[26245ms] DBG ---- MESSAGE_IN
[26246ms] DBG -- BUS_FREE
```

The Read TOC with track 0xAA means "read lead-out area information".
This is currently not implemented, but should be quite simple to add - I'll see about it.

**Comment by PetteriAimonen** [comment] 2023-05-02 17:10
Looks good now, no more unhandled commands in the log. The fix will be part of the next release.

I will add bin/cue support in near future also, but that takes slightly more work so it is tracked in issue #187.

**Closed by PetteriAimonen** 2023-05-02 17:10 UTC
