### ISSUE TITLE
Certain drive images do not show up at all in Drive Setup

### ISSUE THREAD

**Issue by garthbeagle** [ZuluSCSI/ZuluSCSI-firmware#41] opened 2022-08-22 15:37 UTC
I shared an image that reproduces that issue here
https://drive.google.com/file/d/18IblhpvPX7LKZXFjWPuIvFQv_RA9MfPE/view?usp=sharing

To reproduce:
0) Power Macintosh 9600/350, ZuluSCSI 1.1 with 1.0.6-rc2 FW connected to Int SCSI bus, at end of chain along with CD and Zip drives, Term and SW1 switches set on.
1) Format SD card as ExFAT / MBR and copy offending disk image onto it.
2) Boot 9600 off Mac OS 8.6 CD (you can use this copy of 8.6 here https://mega.nz/folder/8hA3AQCJ#pWUq92L70yDXlogy9lk5Dg/folder/ll4HCQQB).
3) Run Drive Setup (1.7.2) off the 8.6 CD.
4) Look for the disk image volume on your ZuluSCSI in the list of devices in Drive Setup.

Results:
The drive image is not shown in the list, thus you cannot initialize/partition the volume.

If I create a brand new image using Disk Jockey (https://bluescsi.onegeekarmy.eu/diskjockey/) I don't see this issue. It's not clear to me what is special about these offending images

**Comment by aperezbios** [comment] 2023-05-28 18:39
@garthbeagle since the original image file no longer exists. and I was unable to ever reproduce this issue, I'm closing this, as we have no way to reproduce it. It would perhaps be interesting to know if this still happens with a current release of firmware, given that there have been many firmware and improvements in the intervening nine months since this issue was filed.

**Closed by aperezbios** 2023-05-28 18:39 UTC
